services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXTAUTH_SECRET=UkUsnFfrzpuB5EggbRmpi0hvrywrcf7r
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=6Lc637QqAAAAAJdDci1aCFZigJZ3y7LhoKH14sOD
      - GOOGLE_SECRET_RECAPTCHA_KEY=6Lc637QqAAAAABjHOIAhF-GqkT89R-9I6ew9MS5P
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dtvxccqrd
      - CLOUDINARY_API_KEY=911759715252164
      - CLOUDINARY_API_SECRET=KtA0TFb3Rbz3XkjuT4fijGIh2tU
      - CLOUDINARY_URL=cloudinary://911759715252164:KtA0TFb3Rbz3XkjuT4fijGIh2tU@dtvxccqrd
      - EMAIL_USER=norwayrsp@gmail.com
      - EMAIL_APP_PASS="zfkz vxmy arfd bckz"
      - NEXT_PUBLIC_GEOAPIFY_KEY=1beaaf78ba084f159ce8bcd3e339040f
      - STRIPE_PUBLISHABLE_KEY=pk_test_51QQF3DFmx2WPpAr0ivNFjrqoZbhZ7gJXWGltI6go8g0ZBb0dz5UpnndrXs6ybiLrNDqcPyuvsPXhfaaWBtzr7nfR00NjCXPGqg
    volumes:
      - .:/app
