"use client";

import { useSession } from "next-auth/react";
import { useEffect, useState, useCallback } from "react";
import { Camera, Phone, Mail, Download, Loader2, Shield, Trash2, AlertTriangle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Membership } from "@/types";
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";


interface PrivacySettings {
	permissionPhotos: boolean;
	permissionPhone: boolean;
	permissionEmail: boolean;
}


export default function PrivacyClient() {
	const { data: session, status } = useSession();
	const { toast } = useToast();
	
	const [privacySettings, setPrivacySettings] = useState<PrivacySettings>({
		permissionPhotos: false,
		permissionPhone: false,
		permissionEmail: false,
	});
	const [isLoading] = useState(true);
	const [isUpdating, setIsUpdating] = useState(false);
	const [isDeleting, setIsDeleting] = useState(false);
	const [membershipData, setMembershipData] = useState<Membership | null>(null);

	const fetchMembershipData = useCallback(async () => {
		try {
			const response = await fetch(`/api/membership?email=${session?.user?.email}`);
			if (!response.ok) {
				throw new Error("Failed to fetch membership data");
			}
			const data = await response.json();
			// Handle case where API returns an array
			let membershipData = data;
			if (Array.isArray(data) && data.length > 0) {
				membershipData = data[0];
			}
			setMembershipData(membershipData);
		} catch (error) {
			console.error("Error fetching membership data:", error);
		}
	}, [session?.user?.email]);

	const fetchPrivacySettings = useCallback(async () => {
		try {
			const response = await fetch("/api/users/privacy-settings");
			if (!response.ok) {
				throw new Error("Failed to fetch privacy settings");
			}
			const data = await response.json();
			setPrivacySettings(data);
		} catch (error) {
			console.error("Error fetching privacy settings:", error);
		}
	}, []);

	// Fetch current privacy settings and membership data
	useEffect(() => {
		if (status === "authenticated") {
			fetchPrivacySettings();
			fetchMembershipData();
		}
	}, [status, fetchPrivacySettings, fetchMembershipData]);

	const handleDownloadMembership = () => {
		if (!membershipData) return;

		// Create membership information content
		const membershipContent = `
MEMBERSHIP INFORMATION
======================

Personal Information:
-------------------
Full Name: ${membershipData.fullName || 'N/A'}
Email: ${membershipData.email || 'N/A'}
Phone: ${membershipData.phone || 'N/A'}
Date of Birth: ${membershipData.dateOfBirth || 'N/A'}
Gender: ${membershipData.gender || 'N/A'}

Address Information:
------------------
Address: ${membershipData.address || 'N/A'}
City: ${membershipData.city || 'N/A'}
Postal Code: ${membershipData.postalCode || 'N/A'}
Province: ${membershipData.province || 'N/A'}
District: ${membershipData.district || 'N/A'}

Professional Information:
-----------------------
Profession: ${membershipData.profession || 'N/A'}
Skills: ${membershipData.skills || 'N/A'}

Membership Details:
------------------
Membership Type: ${membershipData.membershipType || 'N/A'}
Membership Status: ${membershipData.membershipStatus || 'N/A'}
National Membership No: ${membershipData.nationalMembershipNo || 'N/A'}
Registration Date: ${membershipData.createdAt ? new Date(membershipData.createdAt).toLocaleDateString() : 'N/A'}

Volunteer Interests:
------------------
${membershipData.volunteerInterest && membershipData.volunteerInterest.length > 0 
	? membershipData.volunteerInterest.join(', ') 
	: 'No interests specified'}

Permissions:
-----------
Permission to use photos: ${membershipData.permissionPhotos ? 'Yes' : 'No'}
Permission to contact by phone: ${membershipData.permissionPhone ? 'Yes' : 'No'}
Permission to contact by email: ${membershipData.permissionEmail ? 'Yes' : 'No'}

Generated on: ${new Date().toLocaleDateString()}
Generated by: PNSB-Norway Membership System
		`.trim();

		// Create a blob with the content
		const blob = new Blob([membershipContent], { type: 'text/plain' });
		
		// Create download link
		const url = window.URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `${session?.user?.fullName || session?.user?.email || 'user'}-membership-info.txt`;
		
		// Trigger download
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
		
		// Clean up
		window.URL.revokeObjectURL(url);
		
		toast({
			title: "Download Complete",
			description: "Your membership information has been downloaded successfully.",
		});
	};

	
	const handlePrivacyChange = async (field: keyof PrivacySettings, value: boolean) => {
		setIsUpdating(true);
		
		// Optimistic update
		setPrivacySettings(prev => ({ ...prev, [field]: value }));

		try {
			const response = await fetch("/api/users/privacy-settings", {
				method: "PATCH",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify({
					...privacySettings,
					[field]: value,
				}),
			});

			if (!response.ok) {
				throw new Error("Failed to update privacy settings");
			}

			const data = await response.json();
			setPrivacySettings({
				permissionPhotos: data.permissionPhotos,
				permissionPhone: data.permissionPhone,
				permissionEmail: data.permissionEmail,
			});

			toast({
				title: "Success",
				description: "Privacy settings updated successfully",
			});
		} catch (error) {
			console.error("Error updating privacy settings:", error);
			// Revert on error
			setPrivacySettings(prev => ({ ...prev, [field]: !value }));
			toast({
				title: "Error",
				description: "Failed to update privacy settings",
				variant: "destructive",
			});
		} finally {
			setIsUpdating(false);
		}
	};

	const handleDeleteAccount = async () => {
		setIsDeleting(true);
		
		try {
			const response = await fetch("/api/users/delete-account", {
				method: "DELETE",
				headers: {
					"Content-Type": "application/json",
				},
			});

			if (!response.ok) {
				throw new Error("Failed to delete account");
			}

			toast({
				title: "Account Deleted",
				description: "Your account has been permanently deleted. You will be redirected to the login page.",
			});

			// Redirect to login after successful deletion
			setTimeout(() => {
				window.location.href = "/login";
			}, 3000);

		} catch (error) {
			console.error("Error deleting account:", error);
			toast({
				title: "Error",
				description: "Failed to delete account. Please try again.",
				variant: "destructive",
			});
		} finally {
			setIsDeleting(false);
		}
	};

	if (status === "loading" || isLoading) {
		return (
			<div className="max-w-4xl mx-auto">
				<div className="flex items-center justify-center min-h-64">
					<Loader2 className="h-8 w-8 animate-spin text-brand" />
				</div>
			</div>
		);
	}

	if (!session) {
		return (
			<div className="max-w-4xl mx-auto">
				<Alert>
					<Shield className="h-4 w-4" />
					<AlertDescription>
						Please log in to manage your privacy settings.
					</AlertDescription>
				</Alert>
			</div>
		);
	}

	return (
		<div className="max-w-4xl mx-auto space-y-6">
			<div className="mb-8">
				<h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Settings</h1>
				<p className="text-gray-600">
					Control what information is visible to other members and the public.
				</p>
			</div>

			<Card>
				<CardHeader>
					<CardTitle className="flex items-center gap-2">
						<Shield className="h-5 w-5" />
						Visibility Settings
					</CardTitle>
				</CardHeader>
				<CardContent className="space-y-6">
					<div className="flex items-center justify-between p-4 border rounded-lg">
						<div className="flex items-center space-x-3">
							<Camera className="h-5 w-5 text-gray-600" />
							<div>
								<Label htmlFor="photo-visibility" className="font-medium">
									Profile Photo
								</Label>
								<p className="text-sm text-gray-500">
									Allow other members to see your profile photo
								</p>
							</div>
						</div>
						<Switch
							id="photo-visibility"
							checked={privacySettings.permissionPhotos}
							onCheckedChange={(checked: boolean) => 
								handlePrivacyChange("permissionPhotos", checked)
							}
							disabled={isUpdating}
						/>
					</div>

					<div className="flex items-center justify-between p-4 border rounded-lg">
						<div className="flex items-center space-x-3">
							<Phone className="h-5 w-5 text-gray-600" />
							<div>
								<Label htmlFor="phone-visibility" className="font-medium">
									Phone Number
								</Label>
								<p className="text-sm text-gray-500">
									Allow other members to see your phone number
								</p>
							</div>
						</div>
						<Switch
							id="phone-visibility"
							checked={privacySettings.permissionPhone}
							onCheckedChange={(checked: boolean) => 
								handlePrivacyChange("permissionPhone", checked)
							}
							disabled={isUpdating}
						/>
					</div>

					<div className="flex items-center justify-between p-4 border rounded-lg">
						<div className="flex items-center space-x-3">
							<Mail className="h-5 w-5 text-gray-600" />
							<div>
								<Label htmlFor="email-visibility" className="font-medium">
									Email Address
								</Label>
								<p className="text-sm text-gray-500">
									Allow other members to see your email address
								</p>
							</div>
						</div>
						<Switch
							id="email-visibility"
							checked={privacySettings.permissionEmail}
							onCheckedChange={(checked: boolean) => 
								handlePrivacyChange("permissionEmail", checked)
							}
							disabled={isUpdating}
						/>
					</div>
				</CardContent>
			</Card>

						
			{/* Download Membership Information */}
			{membershipData && (
				<div className="flex flex-col sm:flex-row gap-4 my-4">
					<Button
						onClick={() => handleDownloadMembership()}
						variant="outline"
						className="w-fit text-gray-600 hover:bg-gray-50 hover:text-gray-600 border-gray-200"
					>
						<Download className="w-4 h-4 mr-2" />
						Download My Data
					</Button>

					{/* Delete Account Button */}
					<AlertDialog>
						<AlertDialogTrigger asChild>
							<Button
								variant="destructive"
								className="w-fit"
								disabled={isDeleting}
							>
								{isDeleting ? (
									<>
										<Loader2 className="w-4 h-4 mr-2 animate-spin" />
										Deleting...
									</>
								) : (
									<>
										<Trash2 className="w-4 h-4 mr-2" />
										Delete My Account
									</>
								)}
							</Button>
						</AlertDialogTrigger>
						<AlertDialogContent>
							<AlertDialogHeader>
								<AlertDialogTitle className="flex items-center gap-2">
									<AlertTriangle className="h-5 w-5 text-destructive" />
									Delete Account Permanently
								</AlertDialogTitle>
								<AlertDialogDescription>
									<strong className="text-destructive">This action cannot be undone.</strong> Deleting your account will:
									<ul className="mt-2 ml-4 list-disc space-y-1 text-sm">
										<li>Permanently remove your membership information</li>
										<li>Delete your profile and all associated data</li>
										<li>Remove you from all member directories</li>
										<li>Cancel any active memberships or subscriptions</li>
									</ul>
									<p className="mt-3 text-sm">
										Your data will be completely erased from our systems within 30 days, 
										except for information we&apos;re required to keep for legal or accounting purposes.
									</p>
								</AlertDialogDescription>
							</AlertDialogHeader>
							<AlertDialogFooter>
								<AlertDialogCancel>Cancel</AlertDialogCancel>
								<Button
									onClick={handleDeleteAccount}
									variant="destructive"
									disabled={isDeleting}
								>
									{isDeleting ? (
										<>
											<Loader2 className="w-4 h-4 mr-2 animate-spin" />
											Deleting...
										</>
									) : (
										"Delete Account"
									)}
								</Button>
							</AlertDialogFooter>
						</AlertDialogContent>
					</AlertDialog>
				</div>
			)}

			{isUpdating && (
				<div className="flex items-center justify-center p-4">
					<Loader2 className="h-6 w-6 animate-spin text-brand mr-2" />
					<span className="text-sm text-gray-600">Updating settings...</span>
				</div>
			)}
		</div>
	);
}
