"use client";

import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import { Camera, Phone, Mail, Download, Loader2, Shield } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Membership } from "@/types";


interface PrivacySettings {
	permissionPhotos: boolean;
	permissionPhone: boolean;
	permissionEmail: boolean;
}


export default function PrivacyClient() {
	const { data: session, status } = useSession();
	const { toast } = useToast();
	
	const [privacySettings, setPrivacySettings] = useState<PrivacySettings>({
		permissionPhotos: false,
		permissionPhone: false,
		permissionEmail: false,
	});
	const [isLoading, setIsLoading] = useState(true);
	const [isUpdating, setIsUpdating] = useState(false);
	const [membershipData, setMembershipData] = useState<Membership | null>(null);
		

	// Fetch current privacy settings and membership data
	useEffect(() => {
		if (status === "authenticated") {
			fetchPrivacySettings();
			fetchMembershipData();
		}
	}, [status]);

	const handleDownloadMembership = () => {
		if (!membershipData) return;

		// Create membership information content
		const membershipContent = `
MEMBERSHIP INFORMATION
======================

Personal Information:
-------------------
Full Name: ${membershipData.fullName || 'N/A'}
Email: ${membershipData.email || 'N/A'}
Phone: ${membershipData.phone || 'N/A'}
Date of Birth: ${membershipData.dateOfBirth || 'N/A'}
Gender: ${membershipData.gender || 'N/A'}

Address Information:
------------------
Address: ${membershipData.address || 'N/A'}
City: ${membershipData.city || 'N/A'}
Postal Code: ${membershipData.postalCode || 'N/A'}
Province: ${membershipData.province || 'N/A'}
District: ${membershipData.district || 'N/A'}

Professional Information:
-----------------------
Profession: ${membershipData.profession || 'N/A'}
Skills: ${membershipData.skills || 'N/A'}

Membership Details:
------------------
Membership Type: ${membershipData.membershipType || 'N/A'}
Membership Status: ${membershipData.membershipStatus || 'N/A'}
National Membership No: ${membershipData.nationalMembershipNo || 'N/A'}
Registration Date: ${membershipData.createdAt ? new Date(membershipData.createdAt).toLocaleDateString() : 'N/A'}

Volunteer Interests:
------------------
${membershipData.volunteerInterest && membershipData.volunteerInterest.length > 0 
	? membershipData.volunteerInterest.join(', ') 
	: 'No interests specified'}

Permissions:
-----------
Permission to use photos: ${membershipData.permissionPhotos ? 'Yes' : 'No'}
Permission to contact by phone: ${membershipData.permissionPhone ? 'Yes' : 'No'}
Permission to contact by email: ${membershipData.permissionEmail ? 'Yes' : 'No'}

Generated on: ${new Date().toLocaleDateString()}
Generated by: PNSB-Norway Membership System
		`.trim();

		// Create a blob with the content
		const blob = new Blob([membershipContent], { type: 'text/plain' });
		
		// Create download link
		const url = window.URL.createObjectURL(blob);
		const link = document.createElement('a');
		link.href = url;
		link.download = `${session?.user?.fullName || session?.user?.email || 'user'}-membership-info.txt`;
		
		// Trigger download
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
		
		// Clean up
		window.URL.revokeObjectURL(url);
		
		toast({
			title: "Download Complete",
			description: "Your membership information has been downloaded successfully.",
		});
	};

	const fetchMembershipData = async () => {
		try {
			const response = await fetch(`/api/membership?email=${session?.user?.email}`);
			if (!response.ok) {
				throw new Error("Failed to fetch membership data");
			}
			const data = await response.json();
			setMembershipData(data);
		} catch (error) {
			console.error("Error fetching membership data:", error);
		}
	};

	const fetchPrivacySettings = async () => {
		try {
			const response = await fetch("/api/users/privacy-settings");
			if (!response.ok) {
				throw new Error("Failed to fetch privacy settings");
			}
			const data = await response.json();
			setPrivacySettings(data);
		} catch (error) {
			console.error("Error fetching privacy settings:", error);
			toast({
				title: "Error",
				description: "Failed to load privacy settings",
				variant: "destructive",
			});
		} finally {
			setIsLoading(false);
		}
	};

	const handlePrivacyChange = async (field: keyof PrivacySettings, value: boolean) => {
		setIsUpdating(true);
		
		// Optimistic update
		setPrivacySettings(prev => ({ ...prev, [field]: value }));

		try {
			const response = await fetch("/api/users/privacy-settings", {
				method: "PATCH",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify({
					...privacySettings,
					[field]: value,
				}),
			});

			if (!response.ok) {
				throw new Error("Failed to update privacy settings");
			}

			const data = await response.json();
			setPrivacySettings({
				permissionPhotos: data.permissionPhotos,
				permissionPhone: data.permissionPhone,
				permissionEmail: data.permissionEmail,
			});

			toast({
				title: "Success",
				description: "Privacy settings updated successfully",
			});
		} catch (error) {
			console.error("Error updating privacy settings:", error);
			// Revert on error
			setPrivacySettings(prev => ({ ...prev, [field]: !value }));
			toast({
				title: "Error",
				description: "Failed to update privacy settings",
				variant: "destructive",
			});
		} finally {
			setIsUpdating(false);
		}
	};

	if (status === "loading" || isLoading) {
		return (
			<div className="max-w-4xl mx-auto">
				<div className="flex items-center justify-center min-h-64">
					<Loader2 className="h-8 w-8 animate-spin text-brand" />
				</div>
			</div>
		);
	}

	if (!session) {
		return (
			<div className="max-w-4xl mx-auto">
				<Alert>
					<Shield className="h-4 w-4" />
					<AlertDescription>
						Please log in to manage your privacy settings.
					</AlertDescription>
				</Alert>
			</div>
		);
	}

	return (
		<div className="max-w-4xl mx-auto space-y-6">
			<div className="mb-8">
				<h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Settings</h1>
				<p className="text-gray-600">
					Control what information is visible to other members and the public.
				</p>
			</div>

			<Card>
				<CardHeader>
					<CardTitle className="flex items-center gap-2">
						<Shield className="h-5 w-5" />
						Visibility Settings
					</CardTitle>
				</CardHeader>
				<CardContent className="space-y-6">
					<div className="flex items-center justify-between p-4 border rounded-lg">
						<div className="flex items-center space-x-3">
							<Camera className="h-5 w-5 text-gray-600" />
							<div>
								<Label htmlFor="photo-visibility" className="font-medium">
									Profile Photo
								</Label>
								<p className="text-sm text-gray-500">
									Allow other members to see your profile photo
								</p>
							</div>
						</div>
						<Switch
							id="photo-visibility"
							checked={privacySettings.permissionPhotos}
							onCheckedChange={(checked: boolean) => 
								handlePrivacyChange("permissionPhotos", checked)
							}
							disabled={isUpdating}
						/>
					</div>

					<div className="flex items-center justify-between p-4 border rounded-lg">
						<div className="flex items-center space-x-3">
							<Phone className="h-5 w-5 text-gray-600" />
							<div>
								<Label htmlFor="phone-visibility" className="font-medium">
									Phone Number
								</Label>
								<p className="text-sm text-gray-500">
									Allow other members to see your phone number
								</p>
							</div>
						</div>
						<Switch
							id="phone-visibility"
							checked={privacySettings.permissionPhone}
							onCheckedChange={(checked: boolean) => 
								handlePrivacyChange("permissionPhone", checked)
							}
							disabled={isUpdating}
						/>
					</div>

					<div className="flex items-center justify-between p-4 border rounded-lg">
						<div className="flex items-center space-x-3">
							<Mail className="h-5 w-5 text-gray-600" />
							<div>
								<Label htmlFor="email-visibility" className="font-medium">
									Email Address
								</Label>
								<p className="text-sm text-gray-500">
									Allow other members to see your email address
								</p>
							</div>
						</div>
						<Switch
							id="email-visibility"
							checked={privacySettings.permissionEmail}
							onCheckedChange={(checked: boolean) => 
								handlePrivacyChange("permissionEmail", checked)
							}
							disabled={isUpdating}
						/>
					</div>
				</CardContent>
			</Card>

						
			{/* Download Membership Information */}
			{membershipData && (
				<Button
					onClick={() => handleDownloadMembership()}
					variant="outline"
					className="w-fit text-gray-600 hover:bg-gray-50 hover:text-gray-600 border-gray-200 my-4"
				>
					<Download className="w-4 h-4" />
					Download My Data
				</Button>
			)}

			{isUpdating && (
				<div className="flex items-center justify-center p-4">
					<Loader2 className="h-6 w-6 animate-spin text-brand mr-2" />
					<span className="text-sm text-gray-600">Updating settings...</span>
				</div>
			)}
		</div>
	);
}
