import { NextRequest, NextResponse } from "next/server";
import ConnectDB from "@/lib/mongodb";
import EventRegistration from "@/models/EventRegistration.Model";
import Event from "@/models/Event.Model";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/options";

function attendeeSummary(registration: InstanceType<typeof EventRegistration>) {
  return {
    registrationId: registration.registrationId,
    firstName: registration.firstName,
    lastName: registration.lastName,
    email: registration.email,
    phone: registration.phone,
    adults: registration.adults || 0,
    students: registration.students || 0,
    children: registration.children || 0,
    elders: registration.elders || 0,
    totalAttendees: registration.getTotalAttendees(),
    status: registration.status,
    checkedIn: registration.checkedIn,
    checkedInAt: registration.checkedInAt,
    checkedInBy: registration.checkedInBy,
  };
}

function eventSummary(event: InstanceType<typeof Event>) {
  return {
    eventName: event.eventname,
    eventDate: event.eventdate,
    eventTime: event.eventtime,
    eventVenue: event.eventvenue,
  };
}

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    const role = session?.user?.role;
    if (!session?.user || !role || !["admin", "treasurer"].includes(role)) {
      return NextResponse.json({ status: "error", error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const rawQrData: string | undefined = body?.qrData ?? body?.registrationId;

    if (!rawQrData || typeof rawQrData !== "string") {
      return NextResponse.json({ status: "invalid", error: "QR code is empty or unreadable" }, { status: 400 });
    }

    // QR codes generated by this app just encode the bare registrationId string.
    // Some older/foreign QR data could still be JSON, so unwrap that shape too.
    let registrationId = rawQrData.trim();
    try {
      const parsed = JSON.parse(rawQrData);
      if (parsed && typeof parsed.registrationId === "string") {
        registrationId = parsed.registrationId;
      }
    } catch {
      // not JSON, treat rawQrData as the plain registrationId
    }

    await ConnectDB();

    const registration = await EventRegistration.findOne({ registrationId });

    if (!registration) {
      return NextResponse.json({ status: "invalid", error: "This QR code does not match any registration" }, { status: 404 });
    }

    const event = await Event.findById(registration.eventId);
    if (!event) {
      return NextResponse.json({ status: "invalid", error: "Event for this registration no longer exists" }, { status: 404 });
    }

    if (registration.status !== "confirmed") {
      return NextResponse.json({
        status: "invalid",
        error: registration.status === "cancelled" ? "This registration was rejected/cancelled" : "This registration is still pending payment approval",
        registration: attendeeSummary(registration),
        event: eventSummary(event),
      }, { status: 409 });
    }

    if (registration.checkedIn) {
      return NextResponse.json({
        status: "already_checked_in",
        message: "Already checked in",
        registration: attendeeSummary(registration),
        event: eventSummary(event),
      });
    }

    // Mark as checked in
    registration.checkedIn = true;
    registration.checkedInAt = new Date();
    registration.checkedInBy = session.user.email || session.user.name || "admin";
    await registration.save();

    return NextResponse.json({
      status: "success",
      message: "Check-in successful",
      registration: attendeeSummary(registration),
      event: eventSummary(event),
    });
  } catch (error) {
    console.error("QR validation error:", error);
    return NextResponse.json({ status: "error", error: "Internal server error" }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({
    message: "QR validation endpoint is working",
    method: "POST",
    required: { qrData: "The scanned QR text (the registration's registrationId)" },
  });
}
